// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rinvGauss
double rinvGauss(double nu, double lambda);
RcppExport SEXP _MACHINE_rinvGauss(SEXP nuSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(rinvGauss(nu, lambda));
    return rcpp_result_gen;
END_RCPP
}
// MACHINE_pretrain
List MACHINE_pretrain(S4 MACHINE, List sample, const LogicalMatrix obs, const Eigen::SparseMatrix<double> R, const Eigen::MatrixXd dW, const Eigen::SparseMatrix<double> W, const Eigen::SparseMatrix<double> mu, const Eigen::SparseMatrix<double> LD_pairs, const Eigen::SparseMatrix<double> LD_pairs_pop, const double asum_pop, const unsigned int n_chain, const NumericVector temp, const unsigned int pre_mcmc_n, const unsigned int pre_burn_in, const double pre_p, const unsigned int pre_maxiter, const unsigned int pre_miniter, const double stepsize, const unsigned int seed);
RcppExport SEXP _MACHINE_MACHINE_pretrain(SEXP MACHINESEXP, SEXP sampleSEXP, SEXP obsSEXP, SEXP RSEXP, SEXP dWSEXP, SEXP WSEXP, SEXP muSEXP, SEXP LD_pairsSEXP, SEXP LD_pairs_popSEXP, SEXP asum_popSEXP, SEXP n_chainSEXP, SEXP tempSEXP, SEXP pre_mcmc_nSEXP, SEXP pre_burn_inSEXP, SEXP pre_pSEXP, SEXP pre_maxiterSEXP, SEXP pre_miniterSEXP, SEXP stepsizeSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type MACHINE(MACHINESEXP);
    Rcpp::traits::input_parameter< List >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const LogicalMatrix >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type R(RSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type dW(dWSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type LD_pairs(LD_pairsSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type LD_pairs_pop(LD_pairs_popSEXP);
    Rcpp::traits::input_parameter< const double >::type asum_pop(asum_popSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_chain(n_chainSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type pre_mcmc_n(pre_mcmc_nSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type pre_burn_in(pre_burn_inSEXP);
    Rcpp::traits::input_parameter< const double >::type pre_p(pre_pSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type pre_maxiter(pre_maxiterSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type pre_miniter(pre_miniterSEXP);
    Rcpp::traits::input_parameter< const double >::type stepsize(stepsizeSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(MACHINE_pretrain(MACHINE, sample, obs, R, dW, W, mu, LD_pairs, LD_pairs_pop, asum_pop, n_chain, temp, pre_mcmc_n, pre_burn_in, pre_p, pre_maxiter, pre_miniter, stepsize, seed));
    return rcpp_result_gen;
END_RCPP
}
// MACHINE_sampling
List MACHINE_sampling(S4 MACHINE, List sample, const LogicalMatrix obs, const Eigen::SparseMatrix<double> R, const Eigen::MatrixXd dW, const Eigen::SparseMatrix<double> W, const Eigen::SparseMatrix<double> mu, const Eigen::SparseMatrix<double> LD_pairs, const Eigen::SparseMatrix<double> LD_pairs_pop, const int n_chain, const NumericVector temp, const int mcmc_n, const int thin, const double stepsize, const unsigned int seed);
RcppExport SEXP _MACHINE_MACHINE_sampling(SEXP MACHINESEXP, SEXP sampleSEXP, SEXP obsSEXP, SEXP RSEXP, SEXP dWSEXP, SEXP WSEXP, SEXP muSEXP, SEXP LD_pairsSEXP, SEXP LD_pairs_popSEXP, SEXP n_chainSEXP, SEXP tempSEXP, SEXP mcmc_nSEXP, SEXP thinSEXP, SEXP stepsizeSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type MACHINE(MACHINESEXP);
    Rcpp::traits::input_parameter< List >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const LogicalMatrix >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type R(RSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type dW(dWSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type LD_pairs(LD_pairsSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double> >::type LD_pairs_pop(LD_pairs_popSEXP);
    Rcpp::traits::input_parameter< const int >::type n_chain(n_chainSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const int >::type mcmc_n(mcmc_nSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const double >::type stepsize(stepsizeSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(MACHINE_sampling(MACHINE, sample, obs, R, dW, W, mu, LD_pairs, LD_pairs_pop, n_chain, temp, mcmc_n, thin, stepsize, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MACHINE_rinvGauss", (DL_FUNC) &_MACHINE_rinvGauss, 2},
    {"_MACHINE_MACHINE_pretrain", (DL_FUNC) &_MACHINE_MACHINE_pretrain, 19},
    {"_MACHINE_MACHINE_sampling", (DL_FUNC) &_MACHINE_MACHINE_sampling, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_MACHINE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
