# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The inverse Gaussian distribution
#' 
#' @description Random generation for the inverse Gaussian distribution with 
#' parameters \\code{mu} and \\code{lambda}.
#'
#' @usage
#' rinvGauss(mu, lambda)
#' 
#' @param mu The mean parameter. Must be positive.
#' @param lambda The shape parameter. Must be positive.
#' 
#' @details
#' The inverse Gaussian distribution with parameters $mean = \\mu$ and 
#' $shape = \\lambda$ has density
#' $$
#' f(x) = \\sqrt\{\\frac\{\\lambda\}\{2 \\pi x^3\}\} 
#' \\exp \{ -\\frac\{\\lambda (x-\\mu)^2\}\{2 \\mu^2 x\} \}
#' $$
#' 
#' @return A random number from inverse Gaussian distribution.
rinvGauss <- function(nu, lambda) {
    .Call('_MACHINE_rinvGauss', PACKAGE = 'MACHINE', nu, lambda)
}

MACHINE_pretrain <- function(MACHINE, sample, obs, R, dW, W, mu, LD_pairs, LD_pairs_pop, asum_pop, n_chain, temp, pre_mcmc_n = 400L, pre_burn_in = 200L, pre_p = 0.05, pre_maxiter = 10L, pre_miniter = 2L, stepsize = 2, seed = 428L) {
    .Call('_MACHINE_MACHINE_pretrain', PACKAGE = 'MACHINE', MACHINE, sample, obs, R, dW, W, mu, LD_pairs, LD_pairs_pop, asum_pop, n_chain, temp, pre_mcmc_n, pre_burn_in, pre_p, pre_maxiter, pre_miniter, stepsize, seed)
}

MACHINE_sampling <- function(MACHINE, sample, obs, R, dW, W, mu, LD_pairs, LD_pairs_pop, n_chain, temp, mcmc_n = 100L, thin = 1L, stepsize = 2, seed = 428L) {
    .Call('_MACHINE_MACHINE_sampling', PACKAGE = 'MACHINE', MACHINE, sample, obs, R, dW, W, mu, LD_pairs, LD_pairs_pop, n_chain, temp, mcmc_n, thin, stepsize, seed)
}

